# Generated by Django 3.0.6 on 2020-05-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barobaro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='korean_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'kor_food',
            },
        ),
    ]
