# Generated by Django 3.0.6 on 2020-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barobaro', '0002_korean_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='chinese_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cn_food',
            },
        ),
        migrations.CreateModel(
            name='japanese_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jp_food',
            },
        ),
    ]
